#!/usr/bin/env python


ERROR_TF_CAUGHT_EXCEPTION = 40001
